import { describe, it, expect, beforeEach, afterEach } from "vitest";
import express, { Request, Response } from "express";
import rateLimit from "express-rate-limit";

// Helper to set up test express app
function createTestApp() {
  const app = express();
  app.set("trust proxy", 1);
  app.use(express.json());

  const testLimiter = rateLimit({
    windowMs: 60 * 1000,
    max: 3, // Low limit for easy testing
    standardHeaders: true,
    legacyHeaders: false,
    message: { error: "Terlalu banyak permintaan verifikasi. Silakan coba beberapa saat lagi." },
  });

  const CERT_CODE_REGEX = /^CYBER-\d{4}-[A-Z0-9]{6}$/i;

  app.get("/api/certificates/verify/:certificateCode", testLimiter, (req: Request, res: Response) => {
    const { certificateCode } = req.params;

    if (!certificateCode || !CERT_CODE_REGEX.test(certificateCode)) {
      res.status(400).json({ error: "Format kode sertifikat tidak valid." });
      return;
    }

    if (certificateCode === "CYBER-2026-INVALID1") {
      res.status(404).json({ error: "Sertifikat tidak ditemukan atau kode tidak valid." });
      return;
    }

    // Mock certificate with internal sensitive fields
    const mockCert = {
      certificateCode: "CYBER-2026-ABC123",
      userId: "secret_user_uid_12345",
      recipientEmail: "private_user@example.com",
      recipientName: "Budi Santoso",
      learningPathTitle: "Beginner Cybersecurity Learning Path",
      issuedAt: "2026-07-22T00:00:00.000Z",
      status: "active",
      verificationHash: "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855",
      internalNotes: "Generated by system",
    };

    // Public sanitized response
    res.json({
      success: true,
      status: "Sertifikat Valid",
      recipientName: mockCert.recipientName,
      learningPathTitle: mockCert.learningPathTitle,
      issuedAt: mockCert.issuedAt,
      certificateCode: mockCert.certificateCode,
      issuer: "Cyber Academy AI",
      certStatus: mockCert.status,
    });
  });

  return app;
}

describe("Public Certificate Verification Endpoint Security & Rate Limiting", () => {
  let app: ReturnType<typeof createTestApp>;
  let server: any;
  let baseUrl: string;

  beforeEach(async () => {
    app = createTestApp();
    await new Promise<void>((resolve) => {
      server = app.listen(0, "127.0.0.1", () => {
        const address = server.address();
        baseUrl = `http://127.0.0.1:${address.port}`;
        resolve();
      });
    });
  });

  afterEach(async () => {
    if (server) {
      await new Promise<void>((resolve) => server.close(resolve));
    }
  });

  it("returns 400 for invalid certificateCode format", async () => {
    const res = await fetch(`${baseUrl}/api/certificates/verify/INVALID_CODE_123`);
    expect(res.status).toBe(400);
    const body = await res.json();
    expect(body.error).toBe("Format kode sertifikat tidak valid.");
  });

  it("does NOT leak sensitive user fields (userId, email, verificationHash, etc.)", async () => {
    const res = await fetch(`${baseUrl}/api/certificates/verify/CYBER-2026-ABC123`);
    expect(res.status).toBe(200);
    const body = await res.json();

    expect(body.success).toBe(true);
    expect(body.recipientName).toBe("Budi Santoso");
    expect(body.certificateCode).toBe("CYBER-2026-ABC123");

    // Strictly verify no sensitive info leaked
    expect(body.userId).toBeUndefined();
    expect(body.uid).toBeUndefined();
    expect(body.recipientEmail).toBeUndefined();
    expect(body.email).toBeUndefined();
    expect(body.verificationHash).toBeUndefined();
    expect(body.internalNotes).toBeUndefined();
  });

  it("enforces rate limit and returns 429 when requests exceed threshold", async () => {
    // 3 allowed requests
    for (let i = 0; i < 3; i++) {
      const res = await fetch(`${baseUrl}/api/certificates/verify/CYBER-2026-ABC123`);
      expect(res.status).toBe(200);
    }

    // 4th request should trigger 429 Too Many Requests
    const blockedRes = await fetch(`${baseUrl}/api/certificates/verify/CYBER-2026-ABC123`);
    expect(blockedRes.status).toBe(429);
    const body = await blockedRes.json();
    expect(body.error).toBe("Terlalu banyak permintaan verifikasi. Silakan coba beberapa saat lagi.");
  });
});
